### ISSUE TITLE
Fails on special UTF-8 char in header

### ISSUE THREAD

**Issue by Robert-M-Muench** [FourierTransformer/ftcsv#10]
Two files different encoding: normal CSV, UTF-8, where the parsing fails on "Länge"

[utf-8_example.zip](https://github.com/FourierTransformer/ftcsv/files/1513540/utf-8_example.zip)

**Comment by FourierTransformer** [comment]
I don't think this is failing on the UTF-8 character. I looked at utf8.csv and noticed it has "Mac OS 9" line endings which just uses "\r". It was also talked about in [this gist](https://gist.github.com/jennybc/0be7717c2b5b30088811). You can try the suggested workaround from the gist of running the file thorugh mac2unix. I also just created pull request #11 that should fix it (it's a one line fix).

Feel free to give it a try. I'll push it out once I have a test in place.

**Comment by FourierTransformer** [comment]
Ooh, I just ran a "cat" on your file and noticed that it came back with "utf8.csv: UTF-8 Unicode **(with BOM)** text, with CR line terminators". Currently ftcsv doesn't parse out the three BOM bytes at the beginning of files - so it's going to exist in the first header... For a quick fix, you could try using the replace header functionaity to get around it. I'll look into it tomorrow.

**Comment by FourierTransformer** [comment]
I merged the pull request (#11) and it should now work correctly for OS9 line endings and files with BOM!

**Comment by Robert-M-Muench** [comment]
Thanks. The file was saved by OSX Excel as CSV format. Wondering why this is such a mess. Anyway, great that it works now.
