### ISSUE TITLE
Backslash-quoted quotation marks

### ISSUE THREAD

**Issue by johnd0e** [FourierTransformer/ftcsv#13]
I have to work with data which contains quotation marks in fields, e.g.
```
"sample","\"quoted\"","\" mark"
```

Is it possible to support such quotation in ftcsv module?
On upper example it behaves strange: second field appears empty.

And next example even get it crashed:
```
"\"text\"",\"2,"3
```

> ftcsv.lua:255: attempt to perform arithmetic on local 'i' (a nil value)
> stack traceback:
>         C:\Apps\Far3\Profile\Macros\modules\ftcsv.lua:255: in function 'parseString'
>         C:\Apps\Far3\Profile\Macros\modules\ftcsv.lua:398: in function 'parse'
>         ...
>

**Comment by FourierTransformer** [comment]
hmmmm... you could try to replace the backslash with a quote. ftcsv tries to do escaping of quotes with two quotes. I haven't ever tested it out with a quote right at the beginning of the field. I might look into that and see what happens.

**Comment by johnd0e** [comment]
You are right, csv in my case is not correct, so I'll better implement own functions to deal with it.

Still, even in terms of pure csv format, your code behaves wrong with upper data samples and need to be fixed.

**Comment by FourierTransformer** [comment]
I've fixed the related issues and the changes will be available in the next release!
