### ISSUE TITLE
Stripping whitespace and exporting to CSV files?

### ISSUE THREAD

**Issue by fmitha** [FourierTransformer/ftcsv#24]
Hi,

I haven't tested your library yet, but is it possible to use it to strip whitespace from a CSV file? I'm looking for a simple way to rewrite a CSV file with whitespace to a CSV file without whitespace, before importing into SQLite.

And does your library support export to CSV files as well?

I was thinking of something like import CSV files while stripping whitespace. Then exporting "cleaned" date to CSV.

**Comment by FourierTransformer** [comment]
Yes, you should be able to do that with this library! It has in parser and a writer. With the current version, you'd have to parse in the file, trim the white space in the fields, and then write it out.

Hope this helps!
