### ISSUE TITLE
Setting options (but not bufferSize) makes the default of bufferSize unset and produces an error

### ISSUE THREAD

**Issue by ghost** [FourierTransformer/ftcsv#28]
Due to checking only for the existence of an options object (on line 405), setting any option will make that check true. Thereafter, the only check related to `bufferSize` is if `options.bufferSize ~= nil`, which will be the case if we set another option, but not `bufferSize`. This means that if one uses `parseLine` with an options object, but doesn't set the `bufferSize` manually (since one wants to use the default value for that), one will get a very cryptic error message: `bad argument #1 to 'read' (string expected, got nil)`, which requires quite a bit of scanning the code to find the origin of. This would be fixed if we had something like `if options.bufferSize == nil then options.bufferSize = 2^16 end` or similar in that block.

**Comment by FourierTransformer** [comment]
Nice find! It's been a while since an issue has been submitted, but I'm glad it's an easy fix. I hope ftcsv has worked well for you otherwise. I'll be cutting a new release here shortly and it will be available on LuaRocks soon.

Thanks!

**Comment by ghost** [comment]
Thanks for the quick turnaround! Yeah, I need to do some regular csv processing of some fairly large CSVs, and ftcsv is way faster then the CSV handling of penlight, and I like the iterator interface a lot. (But it's not like this issue stopped me from using it, I just created a wrapper to set this one option to the default :P) Cheers!

**Comment by FourierTransformer** [comment]
fixed in v1.2.2, closing this out.
