### ISSUE TITLE
Relaxed pasing

### ISSUE THREAD

**Issue by agladysh** [FourierTransformer/ftcsv#30]
I'd like to be able to parse slightly malformed tab-separated documents:

1) With some empty headers
2) With missing columns on some non-header lines

```tsv
one	two		
v1	v2	v3	va
v4	v5
v6	v7	v8
```

It will be sufficient for my use case if:

1) Relaxed parsing will be off by default
2) A column number will be assigned to the empty header.
3) `nil` will be assigned to missing column value.

**Comment by FourierTransformer** [comment]
Parsing files like that is much harder, and definitely not up to any CSV spec. You can try using https://github.com/geoffleyland/lua-csv, which does support tab delimited files.

I'm not planning to add a "relaxed" parsing mode to ftcsv anytime soon unfortunately. Good luck with those files, they seem pretty wild!
