### ISSUE TITLE
Specify the size of  columns  ???

### ISSUE THREAD

**Issue by lingbl** [FourierTransformer/ftcsv#36]
the head of my tsv file is one columns , but the data is ten columns,  can I specify the size of tsv columns ? 
and If ftcsv can skip some head line is better,  my tsv file is not always formal.

**Comment by FourierTransformer** [comment]
I'm not exactly sure what you mean, it sounds like you have 10 lines you want to skip before parsing. If that's the case, you could try loading the file into memory first, scanning past the header data columns (and make a new string), and then using ftcsv to parse the rest of the file.

Sort've pre-process the file before parsing.

**Comment by lingbl** [comment]
fine , this a way to skip some head lines
